### ISSUE TITLE
SRTM 3.1.10 will not download images

### ISSUE THREAD

**Issue by rlundeen562** [hdus/SRTM-Downloader#19]
The credentials window does not pop up and images are not downloaded.

Tried on:
 QGIS 3.10 on MacOS Big Sur
 QGIS 3.10 on Windows 10
 QGIS 3.16 on Windows 10

**Comment by hdus** [comment]
The used download server of usgs is not available at the moment.

**Comment by ambarja** [comment]
@hdus  Thank a lot  for the information, recently I've used again the plugin I have the same problem :cry:

**Comment by hdus** [comment]
The download URL has changed again and is fixed in the new release. Please close the issue if it is ok.

**Comment by AuSpotter** [comment]
It may be broken again? I now receive this error:

Error transferring https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/<filename for tile>.SRTMGL1.hgt.zip - server replied: Not Found

**Comment by ambarja** [comment]
@AuSpotter  what version of QGIS do you have install on your pc ? 
In my case the plugin functions perfect 
 
![Captura de pantalla de 2021-04-19 18-47-39](https://user-images.githubusercontent.com/23284899/115316867-dc8a6100-a13f-11eb-83f8-877be7a0eabf.png)
![Captura de pantalla de 2021-04-19 18-47-24](https://user-images.githubusercontent.com/23284899/115316876-df855180-a13f-11eb-9658-0f94e1867468.png)

**Comment by AuSpotter** [comment]
I'm using long term release 3.16.5. I just verified that my username and password work (when used directly on the site) so I will update to LTR 3.16.6 and see how that works!

**Comment by AuSpotter** [comment]
OK, I may have found the culprit: high latitudes.

No trouble with South America or continental USA:
![image](https://user-images.githubusercontent.com/49948901/115334530-693d1b00-a150-11eb-9912-d8ecc41c2a6c.png)

But it fails in the Canadian Arctic
![image](https://user-images.githubusercontent.com/49948901/115334581-82de6280-a150-11eb-951f-d35466b0f5d6.png)

**Comment by siiky** [comment]
Not the same problem as these other comments, but it matches the issue's title (except for the version; I'm using the latest, 3.1.13). Maybe it won't be as useful to others, but here it goes anyway.

In my case, the plugin asked for the username/password a few times, even after I would enter them, until eventually telling me that I need an account -- even though I already had an account!

To "fix" it, I disabled the "Extended ASCII" character group on my password manager, and changed my password on the website. Tried downloading the data again and it worked! (This was my very first guess, because it has happened in the past, with the BOINC GUI on Windows)

I don't know if it's a bug with this specific plugin, Qt (if I got it right, it's the GUI library used), or what.
